name: Quinton Maldonado
favicon: null
layout_spectrum: 0.23897
typography_spectrum: 0.37882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcd8d5'
    - '#712c4b'
    - '#d93e3d'
    - '#c4ad7d'
    - '#da7467'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
