name: Quinton Maldonado
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37882
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5d9ca'
    - '#121212'
    - '#322c29'
    - '#a99f8c'
    - '#686053'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
